channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3
  - graphviz =2.42
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7
  - pysam =0.15
  - gatk4 =4.2.5.0
  - plink =1.90b6.21
  - fastqc =0.11.9
  - cutadapt =4.0
  - trim-galore =0.6.5
  - bbmap 
  - star =2.7.10a
  - picard =2.24.0


