####--------------------------------------------------------###
## Please update this file with project-specific information ##
###############################################################

## Path to a file containing list of ONLY the first pair of paired-end fastq samples to be analyzed:
sample_fq_list: {path to file}

## Path to metadata file
meta: {path to file}

## Path to directory of STAR index of reference genome used
STAR_genome: {path to directory}

## Path to reference genome fasta file
genome_fa: {path to file}

## Path to indel file (for GATK's BaseRecalibrator) [1]
indel1: {path to file}

## Path to indel file (for GATK's BaseRecalibrator) [2]
indel2: {path to file}

## Chromosome intervals for GATK
interval: ./config/chr1-22.listA

## List of chromosome positions of HapMap3 SNPs
hapmap3: ./config/lifted_37to38_hapmap3_clean_maf001_noHLA.txt

## List of high LD regions for GRCh38
ld_regions: ./config/noChr_high-LD-regions-hg38-GRCh38.txt

## Path to tools (we may implement built-in dependencies in te future):
fastqc: {path to tool file}
trimgalore: {path to tool file}
bbmap: {path to tool directory}
picard: {path to tool file}
samtools: {path to tool file}
gatk4: {path to tool file}
plink1_9: {path to tool file}
flashpca: {path to tool file}
